substitutions:
  name: "athom-smart-plug-v2"
  friendly_name: "Perro Guardian"
  room: ""
  device_description: "Perro Guardian"
  project_name: "MarioArranz.PerroGuardian"
  project_version: "v1.0.0"
  sensor_update_interval: "10s"
  relay_restore_mode: RESTORE_DEFAULT_ON
  # Límite de corriente en amperios. Enchufe AU = 10. IL, BR, EU, UK, US = 16.
  current_limit: 16
  # Definir un dominio para este dispositivo. p.ej. iot.home.lan (el dispositivo aparecerá como athom-smart-plug-v2.iot.home.lan en los registros DNS/DHCP)
  dns_domain: ".local"
  # Establecer la zona horaria del enchufe inteligente. Útil si el enchufe está en una ubicación diferente al servidor HA. Se puede introducir en formato Unix Country/Area (p.ej. "Australia/Sydney")
  timezone: ""
  # Establecer la duración entre sondeos del servicio SNTP a los servidores ntp.org para actualizarse
  sntp_update_interval: "6h"
  # Servidores de tiempo de red para su región, introducir de menor a mayor prioridad. Para usar servidores locales actualice según zonas o países en: https://www.ntppool.org/zone/@
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"  
  # Habilita conexiones de red más rápidas, conectando al último SSID conocido y evitando un escaneo completo de SSID
  wifi_fast_connect: false
  # Definir el nivel de registro: NONE, ERROR, WARN, INFO, DEBUG (por defecto), VERBOSE, VERY_VERBOSE
  log_level: "INFO"
  # Habilitar o deshabilitar el uso de IPv6 en el dispositivo
  ipv6_enable: false
  # Ocultar el sensor ENERGY que muestra kWh consumidos, sin periodo de tiempo asociado. Se reinicia al reiniciar o reflashear el dispositivo.
  hide_energy_sensor: false
  # Especifica si los pines deben inicializarse lo antes posible con valores conocidos. Se recomienda false cuando hay interruptores, ya que pueden activarse al actualizar el firmware o reiniciar el dispositivo. Por defecto true.
  early_pin_init: true
  # Selección del icono del enchufe. Cambie para reflejar el tipo/país del enchufe en uso; esto actualizará el icono mostrado junto al interruptor
  power_plug_type: "power-socket-us"  # Opciones: power-socket-au | power-socket-ch | power-socket-de | power-socket-eu | power-socket-fr | power-socket-it | power-socket-jp | power-socket-uk | power-socket-us |


########################## Fin de Sustituciones #########################

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  area: "${room}"
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"
  # PlatformIO options removed for ESP32-C3; defaults will be used for the selected board
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(relay).turn_off();
                      break;
                            }
              case 2:{
                      id(relay).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }
        - lambda: |-
            id(internet_fail_count) = 0;

esp32:
  board: esp32c3-devkitm-1

preferences:
  flash_write_interval: 5min

http_request:
  timeout: 10s
  verify_ssl: false

api:

ota:
  - platform: esphome

logger:
  level: ${log_level}
  baud_rate: 0

web_server:
  port: 80
#  versión: 3

network:
  enable_ipv6: ${ipv6_enable}

wifi:
  # Esto crea un AP con el nombre del dispositivo y la MAC sin contraseña.
  ap: {}
  # Permitir reconexión rápida al SSID previamente conectado, omitiendo el escaneo de todos los SSID
  fast_connect: ${wifi_fast_connect}
  # Definir dominio/sufijo DNS para añadir al nombre de host
  domain: "${dns_domain}"
  # Define el modo mínimo de autenticación WiFi aceptado. Use WPA2 si su router lo soporta.
  min_auth_mode: WPA2

mdns:
  disabled: false

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml

# Componentes Dentra - Añade 'Platform - Energy Statistics'
# https://github.com/dentra/esphome-components/tree/master/components/energy_statistics
# external_components:
#   - source: github://dentra/esphome-components

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

interval:
  - interval: 1min
    then:
      - http_request.get:
          url: http://www.google.com/generate_204
          on_error:
            - lambda: 'id(internet_fail_count) += 1;'
          on_response:
            - lambda: 'id(internet_fail_count) = 0;'
      - if:
          condition:
            lambda: 'return id(internet_fail_count) >= 3;'
          then:
            - switch.turn_off: relay
            - delay: 1min
            - lambda: 'App.reboot();'

  - interval: 7d
    then:
      - switch.turn_off: relay
      - delay: 1min
      - lambda: 'App.reboot();'

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: '2'      # 0 = Always_Off. 1 = Restore_Power_Off. 2 = Always_On.
  - id: internet_fail_count
    type: int
    restore_value: yes
    initial_value: '0'

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    icon: mdi:electric-switch
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;

binary_sensor:
  - platform: status
    name: "Status"
    icon: mdi:check-network-outline
    entity_category: diagnostic    

  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
    id: power_button
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
        - ON for at least 4s
        then:
          - button.press: Reset

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  # Informa la intensidad de la señal WiFi/RSSI en dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  # Informa la intensidad de la señal WiFi en %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""

  # Chip de monitorización de potencia CSE7766
  - platform: cse7766
    id: athom_cse7766
    current:
      name: "Current"
      id: plug_current  # ID añadido para poder referenciarlo en otros sensores
      icon: mdi:current-ac
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: if (x < 0.060) return 0.0; else return x;   # Porque el chip informará menos de 3 W cuando no hay carga conectada
      on_value_range:
        - above: ${current_limit}
          then:
            - switch.turn_off: relay

    voltage:
      name: "Voltage"
      id: plug_voltage  # ID añadido para poder referenciarlo en otros sensores
      icon: mdi:sine-wave
      filters:
        - throttle_average: ${sensor_update_interval}

    power:
      name: "Power"
      id: power_sensor
      icon: mdi:power
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: if (x < 3.0) return 0.0; else return x;    # Porque el chip informará menos de 3 W cuando no hay carga conectada

    energy:
      name: "Energy"
      id: energy
      icon: mdi:lightning-bolt
      unit_of_measurement: kWh
      internal: ${hide_energy_sensor}
      filters:
        - throttle: ${sensor_update_interval}
  # Factor de multiplicación de W a kW es 0.001
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
              id(total_energy_sensor).update();

    apparent_power:
      name: "Apparent Power"
      icon: mdi:power
      filters:
        - throttle_average: ${sensor_update_interval}

    reactive_power:
      name: "Reactive Power"
      icon: mdi:flash
      filters:
        - throttle_average: ${sensor_update_interval}

    power_factor:
      name: "Power Factor"
      icon: mdi:percent-outline
      filters:
        - throttle_average: ${sensor_update_interval}

  - platform: template
    name: "Total Energy"
    id: total_energy_sensor
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: mdi:lightning-bolt
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: ${sensor_update_interval}

  - platform: total_daily_energy
    name: "Total Energy Since Boot"
    restore: true
    power_id: power_sensor
    unit_of_measurement: kWh
    icon: mdi:hours-24
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  #    # Componentes Dentra - Defina el id del sensor que proporciona 'Total Energy' usado
  # - platform: "energy_statistics"
  #   total: total_energy_sensor

  #    # Componentes Dentra - Añade 'Energy Today'. Persiste si se reinicia, a diferencia de 'total_daily_energy'
  #   energy_today:
  #     name: "Energy Today"
  #     id: total_energy_today
  #     accuracy_decimals: 3
  #     icon: mdi:hours-24

  #    # Componentes Dentra - Añade 'Energy Yesterday'
  #   energy_yesterday:
  #     name: "Total Energy Yesterday"
  #     id: total_energy_yesterday
  #     icon: mdi:calendar-today
  #     accuracy_decimals: 3

  #    # Componentes Dentra - Añade 'Energy Week'
  #   energy_week:
  #     name: "Total Energy Week"
  #     id: total_energy_week
  #     icon: mdi:calendar-week
  #     accuracy_decimals: 3

  #    # Componentes Dentra - Añade 'Energy Month'
  #   energy_month:
  #     name: "Total Energy Month"
  #     id: total_energy_month
  #     accuracy_decimals: 3
  #     icon: mdi:calendar-month

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config

switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO12
    id: relay
    restore_mode: ${relay_restore_mode}
    icon: mdi:${power_plug_type}

light:
  - platform: status_led
    name: "Status LED"
    id: blue_led
    icon: mdi:lightbulb-outline
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO13

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      icon: mdi:network-pos
      entity_category: diagnostic

  #  Crea un sensor que muestra cuándo se reinició por última vez el dispositivo
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic
#    device_class: timestamp

  #  Crea un sensor del tiempo de actividad del dispositivo, en días, horas, minutos y segundos formateados
  - platform: template
    name: "Uptime"
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(uptime_sensor).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days > 3650 ) {
        return { "Starting up" };
      } else if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }
    icon: mdi:clock-start

time:
  - platform: sntp
    id: sntp_time
  # Definir la zona horaria del dispositivo
    timezone: "${timezone}"
  # Cambiar el intervalo de sincronización del valor por defecto 5min a 6 horas (o según lo establecido en substitutions)
    update_interval: ${sntp_update_interval}
  # Establecer servidores SNTP específicos a usar
    servers: 
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"    
  # Publicar la hora en que el dispositivo se reinició por última vez
    on_time_sync:
      then:
  # Actualizar la hora del último reinicio, pero solo una vez.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
