substitutions:
  name: "athom-smart-plug-v3"
  friendly_name: "Perro Guardian"
  room: ""
  device_description: "Perro Guardian"
  project_name: "MarioArranz.PerroGuardian"
  project_version: "v1.0.0"
  sensor_update_interval: "10s"
  relay_restore_mode: RESTORE_DEFAULT_ON
  current_limit: "16"
  dns_domain: ".local"
  timezone: ""
  sntp_update_interval: "6h"
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"
  wifi_fast_connect: "false"
  log_level: "INFO"
  ipv6_enable: "false"
  hide_energy_sensor: "false"
  early_pin_init: "true"
  power_plug_type: "power-socket-us"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  area: "${room}"
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
              return id(restore_mode) - 1;
        - lambda: |-
            switch (id(restore_mode)) {
              case 1:
                id(relay).turn_off();
                break;
              case 2:
                id(relay).turn_on();
                break;
              default:
                break;
            }
        - lambda: |-
            id(internet_fail_count) = 0;

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

preferences:
  flash_write_interval: 5min

http_request:
  timeout: 10s
  verify_ssl: false

api:

ota:
  - platform: esphome

logger:
  level: ${log_level}
  baud_rate: 0

web_server:
  port: 80

network:
  enable_ipv6: ${ipv6_enable}

wifi:
  ap: {}
  fast_connect: ${wifi_fast_connect}
  domain: "${dns_domain}"
  min_auth_mode: WPA2

mdns:
  disabled: false

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/esp32-configs/athom-smart-plug.yaml

uart:
  rx_pin: GPIO20
  baud_rate: 4800
  parity: EVEN

interval:
  - interval: 1min
    then:
      - http_request.get:
          url: http://www.google.com/generate_204
          on_error:
            - lambda: |-
                id(internet_fail_count) += 1;
          on_response:
            - lambda: |-
                id(internet_fail_count) = 0;
      - if:
          condition:
            lambda: |-
              return id(internet_fail_count) >= 3;
          then:
            - switch.turn_off: relay
            - delay: 1min
            - lambda: |-
                App.reboot();

  - interval: 7d
    then:
      - switch.turn_off: relay
      - delay: 1min
      - lambda: |-
          App.reboot();

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: '2'  # 1 = Always Off, 2 = Always On, 3 = Restore Power Off State

  - id: internet_fail_count
    type: int
    restore_value: yes
    initial_value: '0'

select:
  - platform: template
    name: "Power On State"
    id: power_mode
    optimistic: true
    icon: mdi:electric-switch
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            if (x == "Always Off") {
              id(restore_mode) = 1;
            } else if (x == "Always On") {
              id(restore_mode) = 2;
            } else {
              id(restore_mode) = 3;
            }

binary_sensor:
  - platform: status
    name: "Status"
    icon: mdi:check-network-outline
    entity_category: diagnostic

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    id: power_button
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: |-
          return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""

  - platform: cse7766
    id: athom_cse7766

    current:
      name: "Current"
      id: plug_current
      icon: mdi:current-ac
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: |-
            if (x < 0.060) return 0.0;
            else return x;
      on_value_range:
        - above: ${current_limit}
          then:
            - switch.turn_off: relay

    voltage:
      name: "Voltage"
      id: plug_voltage
      icon: mdi:sine-wave
      filters:
        - throttle_average: ${sensor_update_interval}

    power:
      name: "Power"
      id: power_sensor
      icon: mdi:power
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: |-
            if (x < 3.0) return 0.0;
            else return x;

    energy:
      name: "Energy"
      id: energy
      icon: mdi:lightning-bolt
      unit_of_measurement: kWh
      internal: ${hide_energy_sensor}
      filters:
        - throttle: ${sensor_update_interval}
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
              id(total_energy_sensor).update();

    apparent_power:
      name: "Apparent Power"
      icon: mdi:power
      filters:
        - throttle_average: ${sensor_update_interval}

    reactive_power:
      name: "Reactive Power"
      icon: mdi:flash
      filters:
        - throttle_average: ${sensor_update_interval}

    power_factor:
      name: "Power Factor"
      icon: mdi:percent-outline
      filters:
        - throttle_average: ${sensor_update_interval}

  - platform: template
    name: "Total Energy"
    id: total_energy_sensor
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:lightning-bolt
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: ${sensor_update_interval}

  - platform: total_daily_energy
    name: "Total Energy Since Boot"
    restore: true
    power_id: power_sensor
    unit_of_measurement: kWh
    icon: mdi:hours-24
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config

switch:
  - platform: gpio
    name: "Switch"
    pin: GPIO5
    id: relay
    restore_mode: ${relay_restore_mode}
    icon: mdi:${power_plug_type}

light:
  - platform: status_led
    name: "Status LED"
    id: blue_led
    icon: mdi:lightbulb-outline
    disabled_by_default: true
    pin:
      number: GPIO6
      inverted: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      icon: mdi:network-pos
      entity_category: diagnostic

  - platform: template
    name: "Last Restart"
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  - platform: template
    name: "Uptime"
    entity_category: diagnostic
    lambda: |-
      int seconds = (int) id(uptime_sensor).state;
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds / 60;
      seconds = seconds % 60;

      if (days > 3650) {
        return {"Starting up"};
      } else if (days) {
        return {(String(days) + "d " + String(hours) + "h " + String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else if (hours) {
        return {(String(hours) + "h " + String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else if (minutes) {
        return {(String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else {
        return {(String(seconds) + "s").c_str()};
      }
    icon: mdi:clock-start

time:
  - platform: sntp
    id: sntp_time
    timezone: "${timezone}"
    update_interval: ${sntp_update_interval}
    servers:
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"
    on_time_sync:
      then:
        - if:
            condition:
              lambda: |-
                return id(device_last_restart).state == "";
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda |-
                    return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");